---
- name: Checking vCenter connectivity
  connection: local
  local_action: wait_for host="{{ vcenter }}" port=443 timeout=3 


- import_tasks: vmx-vm-clone.yml
- import_tasks: vm-add-serial.yml
- import_tasks: vm-nics.yml
- import_tasks: vm-mac.yml
- import_tasks: vm-poweron.yml
