---
- name: Update MAC address of the vnic1
  vm_vnic_macaddress:
    vcenter_ip: "{{ vcenter }}"
    vcenter_user: "{{ vuser }}"
    vcenter_password: "{{ vpassword }}"
    vm_name: "{{ inventory_hostname }}_vcp_{{ version }}"
    vnic: 1
    mac: "{{ mac }}"
