---
- name: Change vnics settings for vFPC
  vsphere_guest:
    vcenter_hostname: "{{ vcenter }}"
    username: "{{ vmuser }}"
    password: "{{ vmpassword }}"
    validate_certs: False
    guest: "{{ inventory_hostname }}_vfpc_{{ version }}"
    state: reconfigured
    vm_nic:
      nic2:
        network: "{{ portgroup }}"
        network_type: dvs
    esxi:
      datacenter: VMLAB

- name: Change vnics settings for vCP
  vsphere_guest:
    vcenter_hostname: "{{ vcenter }}"
    username: "{{ vmuser }}"
    password: "{{ vmpassword }}"
    validate_certs: False
    guest: "{{ inventory_hostname }}_vcp_{{ version }}"
    state: reconfigured
    vm_nic:
      nic2:
        network: "{{ portgroup }}"
        network_type: dvs
    esxi:
      datacenter: VMLAB