---
- name: Checking vCenter connectivity
  connection: local
  local_action: wait_for host="{{ vcenter }}" port=443 timeout=3 


- import_tasks: ovftool.yml
- import_tasks: vm-add-nic.yml
- import_tasks: vm-config.yml
- import_tasks: vm-to-template.yml
