---
- name: Add vnic3-8 to FPC
  vm_addnic:
     vcenter_ip: "{{ vcenter }}"
     vcenter_user: "{{ vuser }}"
     vcenter_password: "{{ vpassword }}"
     vm_name: "{{ vmname}}"
     vmnics: "{{ vmnics }}"

  when: vmxtype == "FPC"

- debug: var=result

