---
- name: Add vnic3-8 to FPC
  vm_addnic:
     vcenter_ip: "{{ vcenter }}"
     vcenter_user: "{{ vmuser }}"
     vcenter_password: "{{ vmpassword }}"
     vm_name: "{{ vmname}}"
     vmnics: "{{ vmnics }}"

  when: vmxtype == "FPC"


